import type { LanguageFn } from 'highlight.js'

const langDefMap: { [key: string]: () => Promise<{default: LanguageFn}>} = {
  '1c':             () => import('highlight.js/lib/languages/1c'),
  'abnf':           () => import('highlight.js/lib/languages/abnf'),
  'accesslog':      () => import('highlight.js/lib/languages/accesslog'),
  'actionscript':   () => import('highlight.js/lib/languages/actionscript'),
  'ada':            () => import('highlight.js/lib/languages/ada'),
  'angelscript':    () => import('highlight.js/lib/languages/angelscript'),
  'apache':         () => import('highlight.js/lib/languages/apache'),
  'applescript':    () => import('highlight.js/lib/languages/applescript'),
  'arcade':         () => import('highlight.js/lib/languages/arcade'),
  'arduino':        () => import('highlight.js/lib/languages/arduino'),
  'armasm':         () => import('highlight.js/lib/languages/armasm'),
  'xml':            () => import('highlight.js/lib/languages/xml'),
  'asciidoc':       () => import('highlight.js/lib/languages/asciidoc'),
  'aspectj':        () => import('highlight.js/lib/languages/aspectj'),
  'autohotkey':     () => import('highlight.js/lib/languages/autohotkey'),
  'autoit':         () => import('highlight.js/lib/languages/autoit'),
  'avrasm':         () => import('highlight.js/lib/languages/avrasm'),
  'awk':            () => import('highlight.js/lib/languages/awk'),
  'axapta':         () => import('highlight.js/lib/languages/axapta'),
  'bash':           () => import('highlight.js/lib/languages/bash'),
  'basic':          () => import('highlight.js/lib/languages/basic'),
  'bnf':            () => import('highlight.js/lib/languages/bnf'),
  'brainfuck':      () => import('highlight.js/lib/languages/brainfuck'),
  'c':              () => import('highlight.js/lib/languages/c'),
  'cal':            () => import('highlight.js/lib/languages/cal'),
  'capnproto':      () => import('highlight.js/lib/languages/capnproto'),
  'ceylon':         () => import('highlight.js/lib/languages/ceylon'),
  'clean':          () => import('highlight.js/lib/languages/clean'),
  'clojure':        () => import('highlight.js/lib/languages/clojure'),
  'clojure-repl':   () => import('highlight.js/lib/languages/clojure-repl'),
  'cmake':          () => import('highlight.js/lib/languages/cmake'),
  'coffeescript':   () => import('highlight.js/lib/languages/coffeescript'),
  'coq':            () => import('highlight.js/lib/languages/coq'),
  'cos':            () => import('highlight.js/lib/languages/cos'),
  'cpp':            () => import('highlight.js/lib/languages/cpp'),
  'crmsh':          () => import('highlight.js/lib/languages/crmsh'),
  'crystal':        () => import('highlight.js/lib/languages/crystal'),
  'csharp':         () => import('highlight.js/lib/languages/csharp'),
  'csp':            () => import('highlight.js/lib/languages/csp'),
  'css':            () => import('highlight.js/lib/languages/css'),
  'd':              () => import('highlight.js/lib/languages/d'),
  'markdown':       () => import('highlight.js/lib/languages/markdown'),
  'dart':           () => import('highlight.js/lib/languages/dart'),
  'delphi':         () => import('highlight.js/lib/languages/delphi'),
  'diff':           () => import('highlight.js/lib/languages/diff'),
  'django':         () => import('highlight.js/lib/languages/django'),
  'dns':            () => import('highlight.js/lib/languages/dns'),
  'dockerfile':     () => import('highlight.js/lib/languages/dockerfile'),
  'dos':            () => import('highlight.js/lib/languages/dos'),
  'dsconfig':       () => import('highlight.js/lib/languages/dsconfig'),
  'dts':            () => import('highlight.js/lib/languages/dts'),
  'dust':           () => import('highlight.js/lib/languages/dust'),
  'ebnf':           () => import('highlight.js/lib/languages/ebnf'),
  'elixir':         () => import('highlight.js/lib/languages/elixir'),
  'elm':            () => import('highlight.js/lib/languages/elm'),
  'ruby':           () => import('highlight.js/lib/languages/ruby'),
  'erb':            () => import('highlight.js/lib/languages/erb'),
  'erlang-repl':    () => import('highlight.js/lib/languages/erlang-repl'),
  'erlang':         () => import('highlight.js/lib/languages/erlang'),
  'excel':          () => import('highlight.js/lib/languages/excel'),
  'fix':            () => import('highlight.js/lib/languages/fix'),
  'flix':           () => import('highlight.js/lib/languages/flix'),
  'fortran':        () => import('highlight.js/lib/languages/fortran'),
  'fsharp':         () => import('highlight.js/lib/languages/fsharp'),
  'gams':           () => import('highlight.js/lib/languages/gams'),
  'gauss':          () => import('highlight.js/lib/languages/gauss'),
  'gcode':          () => import('highlight.js/lib/languages/gcode'),
  'gherkin':        () => import('highlight.js/lib/languages/gherkin'),
  'glsl':           () => import('highlight.js/lib/languages/glsl'),
  'gml':            () => import('highlight.js/lib/languages/gml'),
  'go':             () => import('highlight.js/lib/languages/go'),
  'golo':           () => import('highlight.js/lib/languages/golo'),
  'gradle':         () => import('highlight.js/lib/languages/gradle'),
  'graphql':        () => import('highlight.js/lib/languages/graphql'),
  'groovy':         () => import('highlight.js/lib/languages/groovy'),
  'haml':           () => import('highlight.js/lib/languages/haml'),
  'handlebars':     () => import('highlight.js/lib/languages/handlebars'),
  'haskell':        () => import('highlight.js/lib/languages/haskell'),
  'haxe':           () => import('highlight.js/lib/languages/haxe'),
  'hsp':            () => import('highlight.js/lib/languages/hsp'),
  'http':           () => import('highlight.js/lib/languages/http'),
  'hy':             () => import('highlight.js/lib/languages/hy'),
  'inform7':        () => import('highlight.js/lib/languages/inform7'),
  'ini':            () => import('highlight.js/lib/languages/ini'),
  'irpf90':         () => import('highlight.js/lib/languages/irpf90'),
  'isbl':           () => import('highlight.js/lib/languages/isbl'),
  'java':           () => import('highlight.js/lib/languages/java'),
  'javascript':     () => import('highlight.js/lib/languages/javascript'),
  'jboss-cli':      () => import('highlight.js/lib/languages/jboss-cli'),
  'json':           () => import('highlight.js/lib/languages/json'),
  'julia':          () => import('highlight.js/lib/languages/julia'),
  'julia-repl':     () => import('highlight.js/lib/languages/julia-repl'),
  'kotlin':         () => import('highlight.js/lib/languages/kotlin'),
  'lasso':          () => import('highlight.js/lib/languages/lasso'),
  'latex':          () => import('highlight.js/lib/languages/latex'),
  'ldif':           () => import('highlight.js/lib/languages/ldif'),
  'leaf':           () => import('highlight.js/lib/languages/leaf'),
  'less':           () => import('highlight.js/lib/languages/less'),
  'lisp':           () => import('highlight.js/lib/languages/lisp'),
  'livecodeserver': () => import('highlight.js/lib/languages/livecodeserver'),
  'livescript':     () => import('highlight.js/lib/languages/livescript'),
  'llvm':           () => import('highlight.js/lib/languages/llvm'),
  'lsl':            () => import('highlight.js/lib/languages/lsl'),
  'lua':            () => import('highlight.js/lib/languages/lua'),
  'makefile':       () => import('highlight.js/lib/languages/makefile'),
  'mathematica':    () => import('highlight.js/lib/languages/mathematica'),
  'matlab':         () => import('highlight.js/lib/languages/matlab'),
  'maxima':         () => import('highlight.js/lib/languages/maxima'),
  'mel':            () => import('highlight.js/lib/languages/mel'),
  'mercury':        () => import('highlight.js/lib/languages/mercury'),
  'mipsasm':        () => import('highlight.js/lib/languages/mipsasm'),
  'mizar':          () => import('highlight.js/lib/languages/mizar'),
  'perl':           () => import('highlight.js/lib/languages/perl'),
  'mojolicious':    () => import('highlight.js/lib/languages/mojolicious'),
  'monkey':         () => import('highlight.js/lib/languages/monkey'),
  'moonscript':     () => import('highlight.js/lib/languages/moonscript'),
  'n1ql':           () => import('highlight.js/lib/languages/n1ql'),
  'nestedtext':     () => import('highlight.js/lib/languages/nestedtext'),
  'nginx':          () => import('highlight.js/lib/languages/nginx'),
  'nim':            () => import('highlight.js/lib/languages/nim'),
  'nix':            () => import('highlight.js/lib/languages/nix'),
  'node-repl':      () => import('highlight.js/lib/languages/node-repl'),
  'nsis':           () => import('highlight.js/lib/languages/nsis'),
  'objectivec':     () => import('highlight.js/lib/languages/objectivec'),
  'ocaml':          () => import('highlight.js/lib/languages/ocaml'),
  'openscad':       () => import('highlight.js/lib/languages/openscad'),
  'oxygene':        () => import('highlight.js/lib/languages/oxygene'),
  'parser3':        () => import('highlight.js/lib/languages/parser3'),
  'pf':             () => import('highlight.js/lib/languages/pf'),
  'pgsql':          () => import('highlight.js/lib/languages/pgsql'),
  'php':            () => import('highlight.js/lib/languages/php'),
  'php-template':   () => import('highlight.js/lib/languages/php-template'),
  'plaintext':      () => import('highlight.js/lib/languages/plaintext'),
  'pony':           () => import('highlight.js/lib/languages/pony'),
  'powershell':     () => import('highlight.js/lib/languages/powershell'),
  'processing':     () => import('highlight.js/lib/languages/processing'),
  'profile':        () => import('highlight.js/lib/languages/profile'),
  'prolog':         () => import('highlight.js/lib/languages/prolog'),
  'properties':     () => import('highlight.js/lib/languages/properties'),
  'protobuf':       () => import('highlight.js/lib/languages/protobuf'),
  'puppet':         () => import('highlight.js/lib/languages/puppet'),
  'purebasic':      () => import('highlight.js/lib/languages/purebasic'),
  'python':         () => import('highlight.js/lib/languages/python'),
  'python-repl':    () => import('highlight.js/lib/languages/python-repl'),
  'q':              () => import('highlight.js/lib/languages/q'),
  'qml':            () => import('highlight.js/lib/languages/qml'),
  'r':              () => import('highlight.js/lib/languages/r'),
  'reasonml':       () => import('highlight.js/lib/languages/reasonml'),
  'rib':            () => import('highlight.js/lib/languages/rib'),
  'roboconf':       () => import('highlight.js/lib/languages/roboconf'),
  'routeros':       () => import('highlight.js/lib/languages/routeros'),
  'rsl':            () => import('highlight.js/lib/languages/rsl'),
  'ruleslanguage':  () => import('highlight.js/lib/languages/ruleslanguage'),
  'rust':           () => import('highlight.js/lib/languages/rust'),
  'sas':            () => import('highlight.js/lib/languages/sas'),
  'scala':          () => import('highlight.js/lib/languages/scala'),
  'scheme':         () => import('highlight.js/lib/languages/scheme'),
  'scilab':         () => import('highlight.js/lib/languages/scilab'),
  'scss':           () => import('highlight.js/lib/languages/scss'),
  'shell':          () => import('highlight.js/lib/languages/shell'),
  'smali':          () => import('highlight.js/lib/languages/smali'),
  'smalltalk':      () => import('highlight.js/lib/languages/smalltalk'),
  'sml':            () => import('highlight.js/lib/languages/sml'),
  'sqf':            () => import('highlight.js/lib/languages/sqf'),
  'sql':            () => import('highlight.js/lib/languages/sql'),
  'stan':           () => import('highlight.js/lib/languages/stan'),
  'stata':          () => import('highlight.js/lib/languages/stata'),
  'step21':         () => import('highlight.js/lib/languages/step21'),
  'stylus':         () => import('highlight.js/lib/languages/stylus'),
  'subunit':        () => import('highlight.js/lib/languages/subunit'),
  'swift':          () => import('highlight.js/lib/languages/swift'),
  'taggerscript':   () => import('highlight.js/lib/languages/taggerscript'),
  'yaml':           () => import('highlight.js/lib/languages/yaml'),
  'tap':            () => import('highlight.js/lib/languages/tap'),
  'tcl':            () => import('highlight.js/lib/languages/tcl'),
  'thrift':         () => import('highlight.js/lib/languages/thrift'),
  'tp':             () => import('highlight.js/lib/languages/tp'),
  'twig':           () => import('highlight.js/lib/languages/twig'),
  'typescript':     () => import('highlight.js/lib/languages/typescript'),
  'vala':           () => import('highlight.js/lib/languages/vala'),
  'vbnet':          () => import('highlight.js/lib/languages/vbnet'),
  'vbscript':       () => import('highlight.js/lib/languages/vbscript'),
  'vbscript-html':  () => import('highlight.js/lib/languages/vbscript-html'),
  'verilog':        () => import('highlight.js/lib/languages/verilog'),
  'vhdl':           () => import('highlight.js/lib/languages/vhdl'),
  'vim':            () => import('highlight.js/lib/languages/vim'),
  'wasm':           () => import('highlight.js/lib/languages/wasm'),
  'wren':           () => import('highlight.js/lib/languages/wren'),
  'x86asm':         () => import('highlight.js/lib/languages/x86asm'),
  'xl':             () => import('highlight.js/lib/languages/xl'),
  'xquery':         () => import('highlight.js/lib/languages/xquery'),
  'zephir':         () => import('highlight.js/lib/languages/zephir'),
}

const langAliasMap: { [key: string] : string } = {
  'as': 'actionscript',
  'asc': 'angelscript',
  'apacheconf': 'apache',
  'osascript': 'applescript',
  'arm': 'armasm',
  'adoc': 'asciidoc',
  'ahk': 'autohotkey',
  'x++': 'axapta',
  'sh': 'bash',
  'bf': 'brainfuck',
  'capnp': 'capnproto',
  'h': 'c',
  'icl': 'clean',
  'dcl': 'clean',
  'clj': 'clojure',
  'edn': 'clojure',
  'cmake.in': 'cmake',
  'coffee': 'coffeescript',
  'cson': 'coffeescript',
  'iced': 'coffeescript',
  'cls': 'cos',
  'cc': 'cpp',
  'c++': 'cpp',
  'h++': 'cpp',
  'hpp': 'cpp',
  'hh': 'cpp',
  'hxx': 'cpp',
  'cxx': 'cpp',
  'crm': 'crmsh',
  'pcmk': 'crmsh',
  'cr': 'crystal',
  'cs': 'csharp',
  'c#': 'csharp',
  'dpr': 'delphi',
  'dfm': 'delphi',
  'pas': 'delphi',
  'pascal': 'delphi',
  'patch': 'diff',
  'jinja': 'django',
  'bind': 'dns',
  'zone': 'dns',
  'docker': 'dockerfile',
  'bat': 'dos',
  'cmd': 'dos',
  'dst': 'dust',
  'ex': 'elixir',
  'exs': 'elixir',
  'erl': 'erlang',
  'xlsx': 'excel',
  'xls': 'excel',
  'f90': 'fortran',
  'f95': 'fortran',
  'fs': 'fsharp',
  'f#': 'fsharp',
  'gms': 'gams',
  'gss': 'gauss',
  'nc': 'gcode',
  'feature': 'gherkin',
  'golang': 'go',
  'gql': 'graphql',
  'hbs': 'handlebars',
  'html.hbs': 'handlebars',
  'html.handlebars': 'handlebars',
  'htmlbars': 'handlebars',
  'hs': 'haskell',
  'hx': 'haxe',
  'https': 'http',
  'hylang': 'hy',
  'i7': 'inform7',
  'toml': 'ini',
  'jsp': 'java',
  'js': 'javascript',
  'jsx': 'javascript',
  'mjs': 'javascript',
  'cjs': 'javascript',
  'wildfly-cli': 'jboss-cli',
  'jldoctest': 'julia-repl',
  'kt': 'kotlin',
  'kts': 'kotlin',
  'ls': 'lasso',
  'lassoscript': 'lasso',
  'tex': 'latex',
  'mk': 'makefile',
  'mak': 'makefile',
  'make': 'makefile',
  'md': 'markdown',
  'mkdown': 'markdown',
  'mkd': 'markdown',
  'mma': 'mathematica',
  'wl': 'mathematica',
  'm': 'mercury',
  'moo': 'mercury',
  'mips': 'mipsasm',
  'moon': 'moonscript',
  'nt': 'nestedtext',
  'nginxconf': 'nginx',
  'nixos': 'nix',
  'mm': 'objectivec',
  'objc': 'objectivec',
  'obj-c': 'objectivec',
  'obj-c++': 'objectivec',
  'objective-c++': 'objectivec',
  'ml': 'ocaml',
  'scad': 'openscad',
  'pl': 'perl',
  'pm': 'perl',
  'pf.conf': 'pf',
  'postgres': 'pgsql',
  'postgresql': 'pgsql',
  'text': 'plaintext',
  'txt': 'plaintext',
  'pwsh': 'powershell',
  'ps': 'powershell',
  'ps1': 'powershell',
  'pde': 'processing',
  'pp': 'puppet',
  'pb': 'purebasic',
  'pbi': 'purebasic',
  'py': 'python',
  'gyp': 'python',
  'ipython': 'python',
  'pycon': 'python-repl',
  'k': 'q',
  'kdb': 'q',
  'qt': 'qml',
  're': 'reasonml',
  'graph': 'roboconf',
  'instances': 'roboconf',
  'mikrotik': 'routeros',
  'rb': 'ruby',
  'gemspec': 'ruby',
  'podspec': 'ruby',
  'thor': 'ruby',
  'irb': 'ruby',
  'rs': 'rust',
  'scm': 'scheme',
  'sci': 'scilab',
  'console': 'shell',
  'shellsession': 'shell',
  'st': 'smalltalk',
  'stanfuncs': 'stan',
  'do': 'stata',
  'ado': 'stata',
  'p21': 'step21',
  'step': 'step21',
  'stp': 'step21',
  'styl': 'stylus',
  'tk': 'tcl',
  'craftcms': 'twig',
  'vb': 'vbnet',
  'vbs': 'vbscript',
  'v': 'verilog',
  'sv': 'verilog',
  'svh': 'verilog',
  'tao': 'xl',
  'html': 'xml',
  'xhtml': 'xml',
  'rss': 'xml',
  'atom': 'xml',
  'xjb': 'xml',
  'xsd': 'xml',
  'xsl': 'xml',
  'plist': 'xml',
  'wsf': 'xml',
  'svg': 'xml',
  'xpath': 'xquery',
  'xq': 'xquery',
  'yml': 'yaml',
  'zep': 'zephir',
}

function getLangDef(lang: string): null | (() => Promise<{default: LanguageFn}>) {
  if (langDefMap[lang]) {
    return langDefMap[lang]
  }

  if (langAliasMap[lang]) {
    return langDefMap[langAliasMap[lang]]
  }

  return null
}

export { getLangDef }